package com.aidigital.reportconstructor.service.reports.ports;

import com.aidigital.reportconstructor.service.reports.dto.CampaignData;
import com.aidigital.reportconstructor.service.reports.dto.CampaignFrequencies;
import com.aidigital.reportconstructor.service.reports.dto.ClaudeNarrative;
import com.aidigital.reportconstructor.service.reports.dto.ClaudeResults;
import com.aidigital.reportconstructor.service.reports.dto.ClaudeSheetBatch;
import com.aidigital.reportconstructor.service.reports.dto.ClaudeStrategic;
import com.aidigital.reportconstructor.service.reports.dto.ClaudeTactical;
import com.aidigital.reportconstructor.service.reports.dto.AudienceInsightInput;
import com.aidigital.reportconstructor.service.reports.dto.CreativeTakeawayInput;
import com.aidigital.reportconstructor.service.reports.dto.DeviceInsightInput;
import com.aidigital.reportconstructor.service.reports.dto.GeoInsightInput;
import com.aidigital.reportconstructor.service.reports.dto.PublisherObservationInput;

import java.util.List;
import java.util.Map;

/**
 * Abstraction over the Anthropic Claude calls the report engine makes:
 * Batch A (strategic), Batch B (tactical), Batch C (results) plus a small
 * Geo-tab summarisation call.
 *
 * <p>The real client is only registered when {@code ANTHROPIC_API_KEY}
 * is set; otherwise the stub client (the only candidate) is injected
 * and every batch returns empty (so resolvers fall back to {@code "—"}).
 */
public interface ClaudeClient {

	/**
	 * @return true when the client is hitting the real Anthropic API.
	 */
	boolean isLive();

	/**
	 * Batch A — audience age/segments, proposal overview, 4 strategic insights.
	 */
	ClaudeStrategic batchStrategic(CampaignData data, String brief);

	/**
	 * Batch A narrative subset — proposal overview + 4 strategic insights only, with the audience fields
	 * left {@code null}. Used by the slides-from-sheet flow, where {@code audience_age}/{@code audience_segments}
	 * already live in the reviewed sheet (generated by {@link #batchSheet} in step 1), so regenerating them
	 * here would waste tokens on copy that the sheet overlay immediately discards.
	 *
	 * @param data  parsed campaign data driving the strategic context block
	 * @param brief free-text campaign brief used as the {@code === CAMPAIGN BRIEF ===} context section
	 * @return the parsed proposal + strategic-insight copy, with {@code audienceAge}/{@code audienceSegments} null
	 */
	ClaudeStrategic batchStrategicNarrative(CampaignData data, String brief);

	/**
	 * Batch B — per-tactic gender split + weekday/weekend peak windows.
	 */
	ClaudeTactical batchTactical(CampaignData data, String brief);

	/**
	 * Generate Sheet batch — a single call covering only the fields the sheet template consumes:
	 * the Batch A {@code audience_age}/{@code audience_segments} narrative plus the Batch B per-tactic
	 * gender split and weekday/weekend peak windows. The field instructions and parsing mirror Batches A
	 * and B exactly; the Batch A proposal/strategic-insight copy and all Batch C copy are never requested
	 * because the sheet does not use them.
	 *
	 * @param data  parsed campaign data whose plan/tactic context drives the audience and per-tactic estimates
	 * @param brief free-text campaign brief used as the {@code === CAMPAIGN BRIEF ===} context section
	 * @return the parsed audience + per-tactic copy for the sheet
	 */
	ClaudeSheetBatch batchSheet(CampaignData data, String brief);

	/**
	 * Batch C — results overview, thoughts on performance, tactic overviews, plus the frequency
	 * narrative ({@code {{f_oppartunity}} / {{f_fact}} / {{f_storytelling}}}) seeded with {@code frequencies}.
	 *
	 * @param data        parsed campaign data and actual-vs-plan tactic metrics
	 * @param brief       free-text campaign brief used to infer the client's industry
	 * @param frequencies pre-computed planned/actual frequency figures embedded in the frequency narrative
	 * @return the parsed, length-capped Batch C copy
	 */
	ClaudeResults batchResults(CampaignData data, String brief, CampaignFrequencies frequencies);

	/**
	 * Batch D — narrative alignment. A final harmonisation pass run after Batches A and C and after every
	 * per-tactic breakdown batch has produced its copy. It reads the already-generated campaign-level
	 * conclusions plus a read-only digest of the breakdown conclusions and rewrites only the cross-cutting
	 * story fields — the proposal overview, the four strategic insights, the per-group results overviews, the
	 * performance thoughts, and the three frequency-narrative strings — so the deck reads as one storyline
	 * that stays faithful to the brief. The audience fields, per-tactic overviews, and optimisation
	 * recommendations are carried through unchanged.
	 *
	 * <p>The pass is purely additive: on any failure, timeout, empty reply, or a client that is not live, the
	 * originals are returned verbatim, so alignment can only improve the deck, never blank it.
	 *
	 * @param strategic       the Batch A output to align ({@code proposalOverview} + {@code strategicInsights});
	 *                        its audience fields are passed through untouched
	 * @param results         the Batch C output to align ({@code resultsOverviews} + {@code thoughtsOnPerformance}
	 *                        + frequency narrative); its tactic overviews and recommendations pass through untouched
	 * @param breakdownDigest one short line per per-tactic breakdown conclusion (geo/audience/device/creative/
	 *                        publisher), used as read-only context so the aligned narrative reflects and does not
	 *                        contradict the deeper slides; empty when no breakdown sections were selected
	 * @param brief           free-text campaign brief the aligned narrative must stay faithful to
	 * @return the aligned strategic + results records, or the originals verbatim when nothing could be aligned
	 */
	ClaudeNarrative batchAlignNarrative(
			ClaudeStrategic strategic, ClaudeResults results, List<String> breakdownDigest, String brief);

	/**
	 * Publisher-observations batch — the four {@code {{publishers_observation_N_1..4}}} bullets on each
	 * tactic's "Top Publishers" breakdown slide, written from the hand-entered publisher table the user
	 * reviewed in the sheet.
	 *
	 * <p>Each bullet is capped at 155 characters, the slide's text budget. Tactics are sent in small
	 * chunks rather than one call, keeping the reply well inside the output budget — the failure mode
	 * Batch C hit at ~20 tactics, where a truncated reply failed to parse and every bullet rendered blank.
	 * A chunk that fails or fails to parse only drops its own tactics; the rest still get their copy.
	 *
	 * @param inputs one entry per tactic whose publisher table is non-empty; tactics with no rows must not
	 *               be passed, since there is nothing to observe and the copy would be invented
	 * @param brief  free-text campaign brief, used to tie the channel mix back to the campaign's audience
	 * @return tactic number → its four bullets, in slide order; a tactic missing from the map got no usable
	 *         reply and its bullets should render blank rather than fall back to invented copy
	 */
	Map<Integer, List<String>> batchPublisherObservations(List<PublisherObservationInput> inputs, String brief);

	/**
	 * Creative-takeaways batch — the four {@code {{cr_takeaway_tactic N_1..4}}} bullets on each tactic's
	 * "Creative analysis" breakdown slide, written from the hand-entered creative table the user reviewed
	 * in the sheet.
	 *
	 * <p>The first three bullets read the creative mix (capped at 100 characters, the slide's text budget);
	 * the fourth is a recommendation bullet describing an optimisation already made during the flight, and
	 * gets a wider 140-character budget because it has to state both the action and its result. Chunking
	 * and failure behaviour mirror {@link #batchPublisherObservations}: small chunks keep each reply inside
	 * the output budget, and a chunk that fails only drops its own tactics.
	 *
	 * @param inputs one entry per tactic whose creative block is non-empty; tactics with a blank block must
	 *               not be passed, since there is nothing to observe and the copy would be invented
	 * @param brief  free-text campaign brief, used to tie the creative read back to the client's industry
	 * @return tactic number → its four bullets, in slide order; a tactic missing from the map got no usable
	 *         reply and its bullets should render blank rather than fall back to invented copy
	 */
	Map<Integer, List<String>> batchCreativeTakeaways(List<CreativeTakeawayInput> inputs, String brief);

	/**
	 * Geo-insights batch — the four {@code {{geo_insight_N.1..4}}} "what the map tells us" bullets plus the
	 * single {@code {{geo_N_reco}}} recommendation on each tactic's "Geo analysis" breakdown slide, written
	 * from the hand-entered geo table the user reviewed in the sheet.
	 *
	 * <p>Each of the five strings is capped at 140 characters, the slide's text budget. Unlike the creative
	 * and publisher batches — whose recommendations must be framed as something already done during the
	 * flight — the geo recommendation is genuinely forward-looking: it states what we would do next to
	 * improve results (e.g. where to open incremental budget). Chunking and failure behaviour mirror
	 * {@link #batchPublisherObservations}: small chunks keep each reply inside the output budget, and a
	 * chunk that fails only drops its own tactics.
	 *
	 * @param inputs one entry per tactic whose geo block is non-empty; tactics with a blank block must not
	 *               be passed, since there is nothing to observe and the copy would be invented
	 * @param brief  free-text campaign brief, used to tie the geo read back to the campaign's audience/goals
	 * @return tactic number → its five strings (four insights then the recommendation), in slide order; a
	 * tactic missing from the map got no usable reply and its bullets should render blank rather than fall
	 * back to invented copy
	 */
	Map<Integer, List<String>> batchGeoInsights(List<GeoInsightInput> inputs, String brief);

	/**
	 * Audience-insights batch — the four Claude-written strings on each tactic's "Audience analysis"
	 * breakdown slide, written from the hand-entered audience block the user reviewed in the sheet:
	 * the {@code {{aud_N_takeaway}}} key takeaway, the {@code {{aud_N_worked}}} "what worked", the
	 * {@code {{aud_N_flag}}} watch-out, and the {@code {{aud_N_reco}}} recommended action.
	 *
	 * <p>The four strings are returned in that fixed slide order. The takeaway is capped at 256
	 * characters and the other three at 120, the slide's text budgets. The recommendation is
	 * forward-looking — it advises which age groups and segments to lean into next, tied to the
	 * campaign brief. Chunking and failure behaviour mirror {@link #batchGeoInsights}: small chunks
	 * keep each reply inside the output budget, and a chunk that fails only drops its own tactics.
	 *
	 * @param inputs one entry per tactic whose audience block is non-empty; tactics with a blank block
	 *               must not be passed, since there is nothing to observe and the copy would be invented
	 * @param brief  free-text campaign brief, used to tie the audience read back to the campaign's goals
	 * @return tactic number → its four strings (takeaway, what-worked, watch-out, recommendation), in
	 * slide order; a tactic missing from the map got no usable reply and its fields should render blank
	 * rather than fall back to invented copy
	 */
	Map<Integer, List<String>> batchAudienceInsights(List<AudienceInsightInput> inputs, String brief);

	/**
	 * Device-insights batch — the four Claude-written strings on each tactic's "Device breakdown" slide,
	 * written from the hand-entered device block the user reviewed in the sheet: the
	 * {@code {{dev_N_takeaway}}} key takeaway, the {@code {{dev_N_worked}}} "what worked", the
	 * {@code {{dev_N_flag}}} watch-out, and the {@code {{dev_N_reco}}} recommended action.
	 *
	 * <p>The four strings are returned in that fixed slide order. The takeaway is capped at 256
	 * characters and the other three at 120, the slide's text budgets. The recommendation is
	 * forward-looking — it advises which devices to lean into next, tied to the campaign brief.
	 * Chunking and failure behaviour mirror {@link #batchAudienceInsights}: small chunks keep each reply
	 * inside the output budget, and a chunk that fails only drops its own tactics.
	 *
	 * @param inputs one entry per tactic whose device block is non-empty; tactics with a blank block
	 *               must not be passed, since there is nothing to observe and the copy would be invented
	 * @param brief  free-text campaign brief, used to tie the device read back to the campaign's goals
	 * @return tactic number → its four strings (takeaway, what-worked, watch-out, recommendation), in
	 * slide order; a tactic missing from the map got no usable reply and its fields should render blank
	 * rather than fall back to invented copy
	 */
	Map<Integer, List<String>> batchDeviceInsights(List<DeviceInsightInput> inputs, String brief);

	/**
	 * Geo-tab → short ≤40-char comma-separated location string (or null).
	 */
	String summarizeGeo(List<List<String>> geoRows);

	/**
	 * Whole workbook → short comma-separated marketing-funnel-stage string (e.g.
	 * {@code "Awareness, Consideration, Conversion"}), or {@code null}. Used as a fallback when the media
	 * plan carries no explicit funnel/goal column.
	 *
	 * @param geoRows every tab of the media-plan workbook flattened into one grid (same shape as {@link #summarizeGeo})
	 * @return the comma-separated funnel-stage line, or {@code null}
	 */
	String summarizeFunnelStages(List<List<String>> geoRows);

	/**
	 * Media plan → single-line primary-KPIs string (e.g. {@code "Imps, CTR, VCR, R&F"}) reflecting the KPIs
	 * relevant to the campaign's tactic mix, or {@code null} when no tactics/KPIs can be inferred.
	 *
	 * @param data parsed campaign data whose tactic mix drives the KPI selection
	 * @return the comma-separated primary-KPIs line, or {@code null}
	 */
	String summarizePrimaryKpis(CampaignData data);
}
