package com.aidigital.reportconstructor.service.reports.ports;

import com.aidigital.reportconstructor.service.reports.dto.CampaignData;
import com.aidigital.reportconstructor.service.reports.dto.CampaignFrequencies;
import com.aidigital.reportconstructor.service.reports.dto.ClaudeResults;
import com.aidigital.reportconstructor.service.reports.dto.ClaudeSheetBatch;
import com.aidigital.reportconstructor.service.reports.dto.ClaudeStrategic;
import com.aidigital.reportconstructor.service.reports.dto.ClaudeTactical;

import java.util.List;

/**
 * Abstraction over the Anthropic Claude calls the report engine makes:
 * Batch A (strategic), Batch B (tactical), Batch C (results) plus a small
 * Geo-tab summarisation call.
 *
 * <p>The real client is only registered when {@code ANTHROPIC_API_KEY}
 * is set; otherwise the stub client (the only candidate) is injected
 * and every batch returns empty (so resolvers fall back to {@code "—"}).
 */
public interface ClaudeClient {

	/**
	 * @return true when the client is hitting the real Anthropic API.
	 */
	boolean isLive();

	/**
	 * Batch A — audience age/segments, proposal overview, 4 strategic insights.
	 */
	ClaudeStrategic batchStrategic(CampaignData data, String brief);

	/**
	 * Batch A narrative subset — proposal overview + 4 strategic insights only, with the audience fields
	 * left {@code null}. Used by the slides-from-sheet flow, where {@code audience_age}/{@code audience_segments}
	 * already live in the reviewed sheet (generated by {@link #batchSheet} in step 1), so regenerating them
	 * here would waste tokens on copy that the sheet overlay immediately discards.
	 *
	 * @param data  parsed campaign data driving the strategic context block
	 * @param brief free-text campaign brief used as the {@code === CAMPAIGN BRIEF ===} context section
	 * @return the parsed proposal + strategic-insight copy, with {@code audienceAge}/{@code audienceSegments} null
	 */
	ClaudeStrategic batchStrategicNarrative(CampaignData data, String brief);

	/**
	 * Batch B — per-tactic gender split + weekday/weekend peak windows.
	 */
	ClaudeTactical batchTactical(CampaignData data, String brief);

	/**
	 * Generate Sheet batch — a single call covering only the fields the sheet template consumes:
	 * the Batch A {@code audience_age}/{@code audience_segments} narrative plus the Batch B per-tactic
	 * gender split and weekday/weekend peak windows. The field instructions and parsing mirror Batches A
	 * and B exactly; the Batch A proposal/strategic-insight copy and all Batch C copy are never requested
	 * because the sheet does not use them.
	 *
	 * @param data  parsed campaign data whose plan/tactic context drives the audience and per-tactic estimates
	 * @param brief free-text campaign brief used as the {@code === CAMPAIGN BRIEF ===} context section
	 * @return the parsed audience + per-tactic copy for the sheet
	 */
	ClaudeSheetBatch batchSheet(CampaignData data, String brief);

	/**
	 * Batch C — results overview, thoughts on performance, tactic overviews, plus the frequency
	 * narrative ({@code {{f_oppartunity}} / {{f_fact}} / {{f_storytelling}}}) seeded with {@code frequencies}.
	 *
	 * @param data        parsed campaign data and actual-vs-plan tactic metrics
	 * @param brief       free-text campaign brief used to infer the client's industry
	 * @param frequencies pre-computed planned/actual frequency figures embedded in the frequency narrative
	 * @return the parsed, length-capped Batch C copy
	 */
	ClaudeResults batchResults(CampaignData data, String brief, CampaignFrequencies frequencies);

	/**
	 * Geo-tab → short ≤40-char comma-separated location string (or null).
	 */
	String summarizeGeo(List<List<String>> geoRows);

	/**
	 * Whole workbook → short comma-separated marketing-funnel-stage string (e.g.
	 * {@code "Awareness, Consideration, Conversion"}), or {@code null}. Used as a fallback when the media
	 * plan carries no explicit funnel/goal column.
	 *
	 * @param geoRows every tab of the media-plan workbook flattened into one grid (same shape as {@link #summarizeGeo})
	 * @return the comma-separated funnel-stage line, or {@code null}
	 */
	String summarizeFunnelStages(List<List<String>> geoRows);

	/**
	 * Media plan → single-line primary-KPIs string (e.g. {@code "Imps, CTR, VCR, R&F"}) reflecting the KPIs
	 * relevant to the campaign's tactic mix, or {@code null} when no tactics/KPIs can be inferred.
	 *
	 * @param data parsed campaign data whose tactic mix drives the KPI selection
	 * @return the comma-separated primary-KPIs line, or {@code null}
	 */
	String summarizePrimaryKpis(CampaignData data);
}
